In [2]:
num1 = 4
num1

4

Importaos la librería de pandas

In [4]:
import pandas as pd

Creamos datos para el Dataframe

In [5]:
datos = {
    'Nombres' : ['Ana','Adian','Lucia','Antonia'],
    'Edad' : [23,25,12,40],
    'Ciudades':['Madrid', 'Sevilla','Toledo','Gijon']
}

Creamos un Dataframe con los datos

In [7]:
df = pd.DataFrame(datos)
df

   Nombres  Edad Ciudades
0      Ana    23   Madrid
1    Adian    25  Sevilla
2    Lucia    12   Toledo
3  Antonia    40    Gijon

Voy a filtrar Datos por edad

In [8]:
df[df['Edad'] > 24]

   Nombres  Edad Ciudades
1    Adian    25  Sevilla
3  Antonia    40    Gijon