In [2]:
import pandas as pd

Creamos un diccionario con paises

In [3]:
dataPaises = {
    "pais": ["España", "Francia","Colomnia","Mexico","peru"],
    "capital": ["Madrid","Paris","Bogota","Ciudad de Mexico","Lima"],
    "superficie":[1.9,2.6,3.9,4.0,2.8]
}

Creamos un DataFrame con el Diccionario

In [5]:
df = pd.DataFrame(dataPaises)
df

       pais           capital  superficie
0    España            Madrid         1.9
1   Francia             Paris         2.6
2  Colomnia            Bogota         3.9
3    Mexico  Ciudad de Mexico         4.0
4      peru              Lima         2.8

In [6]:
df[['capital']]

            capital
0            Madrid
1             Paris
2            Bogota
3  Ciudad de Mexico
4              Lima

Podemos dibujar mas de una columna

In [7]:
df[['capital','superficie']]

            capital  superficie
0            Madrid         1.9
1             Paris         2.6
2            Bogota         3.9
3  Ciudad de Mexico         4.0
4              Lima         2.8

Se pueden seleciionar filas por posición del índice Primero incluido y el segundo no incluido

In [10]:
df[2:5]

  index      pais           capital  superficie
2    CO  Colomnia            Bogota         3.9
3    MX    Mexico  Ciudad de Mexico         4.0
4    PE      peru              Lima         2.8

Por defecto,  los índices de los elementos don númericos y los pone autómaticamente.
Podemos crear nuestros propios indices y sustituir en index

In [ ]:
df.index =["ES","FR","CO","MX","PE"]
df=df.reset_index()
df

   level_0 index      pais           capital  superficie
ES      ES    ES    España            Madrid         1.9
FR      FR    FR   Francia             Paris         2.6
CO      CO    CO  Colomnia            Bogota         3.9
MX      MX    MX    Mexico  Ciudad de Mexico         4.0
PE      PE    PE      peru              Lima         2.8

In [17]:
df["FR":"PE"]

   level_0 index      pais           capital  superficie
FR      FR    FR   Francia             Paris         2.6
CO      CO    CO  Colomnia            Bogota         3.9
MX      MX    MX    Mexico  Ciudad de Mexico         4.0
PE      PE    PE      peru              Lima         2.8